from estructura_de_datos import Stack, Deque, BinaryTree, TreeNode

def main():
    #ejercicio 1
    stack = Stack()
    stack.push(10)
    stack.push(20)
    stack.push(30)
    stack.print_stack()
    print("---------")
    print(f"Removed node: {stack.pop()}")
    print("---------")
    stack.print_stack()
    print("---------")
    print(f"Removed node: {stack.pop()}")
    print(f"Removed node: {stack.pop()}")
    print(f"Removed node: {stack.pop()}")
    
    # ejercicio 2
    print("---------")
    deque = Deque()
    deque.push_left(0)
    deque.push_left(-10)
    deque.push_left(-20)
    deque.print_deque()
    print("---------")
    deque.push_right(10)
    deque.push_right(20)
    deque.print_deque()
    print("---------")
    print(f"Removed node: {deque.pop_left()}")
    deque.print_deque()
    print("---------")
    print(f"Removed node: {deque.pop_right()}")
    deque.print_deque()
    print("---------")
    print(f"Removed node: {deque.pop_left()}")
    print(f"Removed node: {deque.pop_left()}")
    print(f"Removed node: {deque.pop_left()}")
    print(f"Removed node: {deque.pop_left()}")
    deque.print_deque()
    
    # ejercicio 3
    print("---------")
    tree = BinaryTree()
    tree.root = TreeNode(0)
    tree.root.left = TreeNode(-10)
    tree.root.right = TreeNode(10)
    tree.print_tree()
    
main()